### ISSUE TITLE
I installed according to the above requirements, but it depends on the operation

### ISSUE THREAD

**Issue by github-oneyue** [Endelon-Hosting/CloudPanelApi#2]
My current operating system is ub22.04, and I have installed version 2.3.1 of cloudpanel. I have downloaded and installed API services, and it seems to be working properly. However, I have http://ip:9999 No interface displayed. There hasn't been anything on SSH either. Please help me, I really need this program. thanks.
![image](https://github.com/Endelon-Hosting/CloudPanelApi/assets/74414063/298fac90-2a3b-4f14-bda5-a5d04e5cc158)
And I have already opened the port of 9999

**Comment by Masu-Baumgartner** [comment]
There is no interface. This is just shown in the dev enviroment. If you set everything up correctly it should display an 404 when you access it
